name: CMake release build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create build dir
      run: cmake -E make_directory ${{ runner.workspace }}/build
    - name: Configure
      working-directory: ${{ runner.workspace }}/build
      run: cmake ${{ github.workspace }} -DCMAKE_BUILD_TYPE=Release
    - name: Build
      working-directory: ${{ runner.workspace }}/build
      run: cmake --build . --config Release
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: HttpConnection
        path: ${{ runner.workspace }}/HttpConnection
    - name: Release snapshot
      id: release-snapshot
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.date.outputs.date }}
        release_name: ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false
